apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: markenx-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DeividN21/devops-argocd.git
    targetRevision: main
    path: k8s/

  destination:
    server: https://kubernetes.default.svc
    namespace: markenx

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
