apiVersion: apps/v1
kind: Deployment
metadata:
  name: markenx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: markenx-app
  template:
    metadata:
      labels:
        app: markenx-app
    spec:
      containers:
        - name: django-container
          image: markenx/markenx-django:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: launchdarkly-secret
                  key: LD_SDK_KEY
