apiVersion: v1
kind: Service
metadata:
  name: markenx-service
spec:
  type: NodePort # Expone el servicio en un puerto accesible de la IP de Minikube
  selector:
    app: markenx-app
  ports:
    - protocol: TCP
      port: 8000       # El puerto del servicio
      targetPort: 8000 # El puerto del contenedor
      nodePort: 30007 